### ISSUE TITLE
Practice fix bug

### ISSUE THREAD

**Issue by Logboy2000** [decoder0007/PosBor#6]
When respawning at a checkpoint the gamemode and speed will change and deleting the checkpoint causes you to respawn at the checkpoint you deleted. The only fix i cloud find was to exit practice mode and try again

**Comment by decoder0007** [comment]
Hmm. Don’t use the integrated practice fix ig. I’m away in Greece atm so I’ll fix it in a week or so when I get back. As an alternative you can use the one in MHV7 or Figs here: https://github.com/FigmentBoy/Checkpoint-Fix
